// Generated by CoffeeScript 2.7.0
(function() {
  // Simple test using Node's test runner with CommonJS
  var assert, test;

  ({test} = require('node:test'));

  assert = require('node:assert');

  test('basic math', function() {
    return assert.equal(1 + 1, 2);
  });

  test('async test', async function() {
    await new Promise(function(resolve) {
      return setTimeout(resolve, 10);
    });
    return assert.ok(true, 'Async works');
  });

  test('objects', function() {
    var obj;
    obj = {
      a: 1,
      b: 2
    };
    return assert.deepEqual(obj, {
      a: 1,
      b: 2
    });
  });

}).call(this);
